### ISSUE TITLE
✨ [24.12.17] 광고주, 인플루언서 페이지 UI 오류 수정

### ISSUE THREAD

**Issue by hyeji17** [wailead/next-seo#120]
## Todo

- [x] 링크버튼 클릭시 이동위치 지정
#### 광고주 페이지
- [x] about : transition 적용
- [x] our services : 아이템 배치 수정
- [x] performance, about, 서비스 소개 : 배경 레이아웃 수정
#### 인플루언서 페이지
- [x] introduction : 등급 이미지 간격 조정
- [x] introduction : 원하는 날짜에 신청가는 달력 이미지 위치 조정
