### ISSUE TITLE
✨ [24.12.26] 헤더 및 introduction, question 반응형 구현

### ISSUE THREAD

**Issue by hyeji17** [wailead/next-seo#143]
## Todo

- [x] 헤더 버튼간의 간격 수정 및 로고 위치 수정
- [x] introduction 반응형 구현
- [x] question 반응형 구현
