### ISSUE TITLE
✨ [24.12.05] MainHeader 배경 경로 변경 및 Youtube 자동재생

### ISSUE THREAD

**Issue by BomJin2** [wailead/next-seo#60]
## Todo

- [x] 배경 경로 변경
- [x] Youtube 자동 재생
- [ ] 이미지 크기 조절
