### ISSUE TITLE
✨ [24.12.08] 광고주 페이지 - 배너

### ISSUE THREAD

**Issue by lumpenop** [wailead/next-seo#86]
## Todo

- [x] 광고주 페이지를 home 으로 변경
- [x] 광고주 페이지 우수기업 선정 배너
- [x] 기업 로고 이미지 정리
- [x] 광고주 페이지 기업 로고 배너
