### ISSUE TITLE
✨ [24.12.09] 헤더 및 introduction, question 수정

### ISSUE THREAD

**Issue by hyeji17** [wailead/next-seo#93]
## 작업 사항

헤더 및 introduction, question UI 수정

## Todo

- [x] 헤더 위치 고정 및 패딩 주기
- [x] introduction 이미지 경로 및 introductionBox UI 수정
- [x] Question box 애니메이션 주기
